spring.application.name=AlumniConnect

# MongoDB Atlas URI
spring.data.mongodb.uri=${MONGODB_URI}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION:3600000}

# Cloudinary
cloudinary.cloud_name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api_key=${CLOUDINARY_API_KEY}
cloudinary.api_secret=${CLOUDINARY_API_SECRET}

# Server port
server.port=${PORT:8080}

# MongoDB SSL
spring.data.mongodb.ssl.enabled=true
spring.data.mongodb.ssl.invalid-hostname-allowed=true